live_config_reload = true

[window]
dimensions = { columns = 110, lines = 32}
padding = { x = 8, y = 8 }
decorations = "Full"
dynamic_padding = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 9.5

[colors]
  # Colors (Gruvbox Material Medium Dark)

  # Default colors
  [colors.primary]
  background = '#282828'
  foreground = '#d4be98'

  # Normal colors
  [colors.normal]
  black   = '#3c3836'
  red     = '#ea6962'
  green   = '#a9b665'
  yellow  = '#d8a657'
  blue    = '#7daea3'
  magenta = '#d3869b'
  cyan    = '#89b482'
  white   = '#d4be98'

  # Bright colors (same as normal colors)
  [colors.bright]
  black   = '#3c3836'
  red     = '#ea6962'
  green   = '#a9b665'
  yellow  = '#d8a657'
  blue    = '#7daea3'
  magenta = '#d3869b'
  cyan    = '#89b482'
  white   = '#d4be98'


  #  My custom Monokai Color Theme
  #
  #  [colors.primary]
  #  background = "#272822"
  #  foreground = "#fff1f3"
  #
  #  [colors.normal]
  #  black   = "#2c2525"
  #  red     = "#ff4e6e"
  #  green   = "#A9DC76"
  #  yellow  = "#f9cc6c"
  #  blue    = "#4cc743"
  #  magenta = "#a8a9eb"
  #  cyan    = "#85dacc"
  #  white   = "#fff1f3"
  #
  #  [colors.bright]
  #  black   = "#414141"
  #  red     = "#ff8198"
  #  green   = "#b6df85"
  #  yellow  = "#fbdd9d"
  #  blue    = "#71d36a"
  #  magenta = "#d1d2f5"
  #  cyan    = "#ace6dc"
  #  white   = "#ffffff"
  #
  #  [colors.dim]
  #  black = "#000000"
  #  red = "#712b2b"
  #  green = "#9ed45d"
  #  yellow = "#a17e4d"
  #  blue = "#1e571a"
  #  magenta = "#704d68"
  #  cyan = "#4d7770"
  #  white = "#8e8e8e"
