#!/bin/bash

## Files and cmd
CFG="$HOME/.config/eww/powermenu"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open power-buttons
}

run_eww
