general {
    # Lock command: What to run when the system locks
    lock_cmd = pidof hyprlock || hyprlock

    # Before suspend: Lock the screen first!
    before_sleep_cmd = loginctl lock-session

    # After suspend: Turn the screen back on
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ----------------------------------------------------------------------------------------------------------
# 5 MINUTES: DIM SCREEN & KEYBOARD OFF
# ----------------------------------------------------------------------------------------------------------
listener {
    timeout = 300
    # Save brightness set to 10%
    on-timeout = brightnessctl -s set 10%
    # Restore brightness from the saved file
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    # Turn off keyboard backlight
    on-timeout = brightnessctl -sd *::kbd_backlight set 0
    # Restore keyboard backlight
    on-resume = brightnessctl -rd *::kbd_backlight
}

# ----------------------------------------------------------------------------------------------------------
# 7 MINUTES: LOCK SCREEN
# ----------------------------------------------------------------------------------------------------------
listener {
    timeout = 420
    on-timeout = loginctl lock-session
}

# ----------------------------------------------------------------------------------------------------------
# 10 MINUTES: SCREEN OFF (DPMS)
# ----------------------------------------------------------------------------------------------------------
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# ----------------------------------------------------------------------------------------------------------
# 1 HOUR: SUSPEND
# ----------------------------------------------------------------------------------------------------------
listener {
    timeout = 3600                               # 1 hour
    on-timeout = systemctl suspend
}
