#!/bin/bash

~/.config/herbstluftwm/configs/setup
~/.config/herbstluftwm/configs/keybinds
~/.config/herbstluftwm/configs/theme

~/.config/eww/launch.sh
# ~/.config/herbstluftwm/scripts/spotify/playerctl_launcher.sh
~/.config/herbstluftwm/scripts/late_monitor_detect.sh &
~/.config/herbstluftwm/services/start_services.sh
