#!/bin/bash

pgrep -x picom >/dev/null || picom --backend glx --vsync -b # Picom compositor

~/.config/herbstluftwm/configs/setup
~/.config/herbstluftwm/configs/keybinds
~/.config/herbstluftwm/configs/theme

~/.config/eww/launch.sh
# ~/.config/herbstluftwm/scripts/spotify/playerctl_launcher.sh
~/.config/herbstluftwm/scripts/late_monitor_detect.sh &

dunst & # notification manager
blueman-applet & # bluetooth manager

xautolock -time 5 -locker "betterlockscreen --lock blur" & # Autolock after 5 minutes of inactivity
~/.config/herbstluftwm/services/start_services.sh
