#!/bin/bash

hc() {
    herbstclient "$@"
}

# ------- Montior setup ----------
# Configured with the help of https://blog.summercat.com/configuring-mixed-dpi-monitors-with-xrandr.html

xrandr --dpi 118
xrandr --output eDP-1 --mode 2560x1440 --pos 440x1440 --primary

# OST Widescreen setup
# xrandr --output DP-1 --mode 3440x1440 --pos 0x0

# Home Setup
# xrandr --output DP-2 --scale 1.25x1.25 --mode 1920x1080 --pos 0x0

# OST SA Room
# xrandr --output DP-1  --mode 1920x1080 --pos 0x0

# detect if monoitor setup has changed
autorandr --change

hc emit_hook reload

# --------- rules ---------
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

# auto-assign certain applications to tags
hc rule class='thunderbird-esr' tag=8 focus=off
hc rule class='teams-for-linux' tag=8 focus=off
hc rule class='thunderbird' tag=8 focus=off


# float and give focus to important windows (use xprop)
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class="Gnome-screenshot" floating=on # float screenshot app
hc rule class="Onboard" floating=on # float virtual keyboard app
hc rule title="Qalculate!" floating=on # float calculator app
hc rule title="splash" floating=on # jetbrains splash screens
hc rule title="Picture-in-Picture" sticky=on # sticky PIP app
hc rule title="blueman-manager" floating=on # sticky PIP app


# hc rule fixedsize floating=on

# One of these regulates the direction new windows open
hc set_layout vertical
hc set default_frame_layout horizontal

hc set focus_follows_mouse 1

hc set tree_style '╾│ ├└╼─┐'


# unlock, just to be sure
hc unlock
