#!/bin/bash

## Files and cmd
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 0.3
fi

## Open widgets
toggle_menu() {
    if ${EWW} active-windows | grep -q "power-buttons"; then
        ${EWW} close power-buttons
        ${EWW} update powermenu-visible=visible-powermenu
    else
        ${EWW} open power-buttons
        ${EWW} update powermenu-visible=invisible-powermenu
    fi
}

toggle_menu
