#!/bin/bash

hc() {
    herbstclient "$@"
}

# ------- Montior setup ----------

# OST Widescreen setup
# xrandr --output eDP-1 --mode 2560x1440 --pos 440x1440 --primary
# xrandr --output DP-1 --mode 3440x1440 --pos 0x0

# Home Setup
xrandr --output eDP-1 --mode 2560x1440 --pos 440x1440 --primary
xrandr --output DP-2 --mode 1920x1080 --pos 0x0

# --------- Panel Settings ---------
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done

hc emit_hook reload

# --------- rules ---------
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class="Gnome-screenshot" floating=on # float screenshot app
hc rule class="Onboard" floating=on # float virtual keyboard app

hc rule fixedsize floating=on

# One of these regulates the direction new windows open
hc set_layout vertical
hc set default_frame_layout horizontal

hc set focus_follows_mouse 1

hc set tree_style '╾│ ├└╼─┐'


# unlock, just to be sure
hc unlock
