#!/bin/bash

hc() {
    herbstclient "$@"
}

# ------- Montior setup ----------

xrandr --output eDP-1 --mode 2560x1440 --pos 440x1440 --primary
xrandr --output DP-1 --mode 3440x1440 --pos 0x0
hc detect_monitors


# --------- Panel Settings ---------
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done

hc emit_hook reload

# EWW
# eww daemon
# eww reload
# eww open bar
#
# --------- rules ---------
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc set_layout vertical

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock
