#!/bin/bash

~/.config/herbstluftwm/configs/setup
~/.config/herbstluftwm/configs/keybinds
~/.config/herbstluftwm/configs/theme


~/.config/herbstluftwm/scripts/battery/battery_health_launcher.sh &
~/.config/eww/launch.sh &
